### ISSUE TITLE
Uncaught ReferenceError: effect is not defined 

### ISSUE THREAD

**Issue by alvarobyrne** [nbriz/threejs_playGnd#11]
That error is shown by dev tools console when loading main page: it happens both when cloning it into my computer and at the online page.

case sensitive searched for full word 'effect' in all project and just found it at main indext.html and at codemirror.js.

(Wanted to label this as question but could not)

**Comment by nbriz** [comment]
what does the code on the line of the error look like?

**Comment by alvarobyrne** [comment]
It's line 162 of index.html:
effect.setSize( window.innerWidth, window.innerHeight );

**Comment by nbriz** [comment]
ah, ok. i think that's just code i left in from b4 ( when there was an effect ) u can just delete that line

**Comment by alvarobyrne** [comment]
thanks
