### ISSUE TITLE
Archive not working

### ISSUE THREAD

**Issue by ghost** [nbriz/threejs_playGnd#14]
It seems the three.js library has been moved from https://www.brangerbriz.com/labs/threejs_playGnd/js/three.min.js
and is causing every sketch in the archive to break.

**Comment by ghost** [comment]
I've done some more digging and discovered the newly archived sketches work well as they have the updated link to three.js (see this [example](http://threejsplaygnd.brangerbriz.com/editor/?id=id7961#B/nVTfT9swEH4uf8XRvQQpJGVbpamUShMU+jAGokjVHt34GpsldnZ2yFrE/z7bSYAO7WVR0zj34/vO9108Pby4Ob//cTsHYctidjBtH4OpQMbdczAt0TLIBCOD9mxY283xl2FwGLst0K8Ga8238ORXgzXLfuaka8WPM11omsCHTbhOg7tklEs1gVH7qh+RNoVuJiAk56iC9dmDpz36NO0qmXoWTxe4M5KVBUPZ2VBYW03S1ApCfDBVwba54smamMqR1iR3iUKbPpg2IimlSh7McOYoAsjsv/Eu0GJmNf0LbnbgtyM3EMEhvAQ3uM4LOHo1MM6v0K5wffXtGo1hOUZHoRH+fmQEGSuRWAwmQ4UxECqOhHTa+3PUTiTaxlAyiyRZ4VZoxGng39Qqs1IrcPrVVXTkhAq995krOINGKq6bRCqFtJLcihgWf5kXKHNhW8l6dheisIH7xd18noTi7zpPV/1LZOKIl3KHEaw8dOflOqtLVDbxsiasqlz0uZAFj142mHBdzgv0UT4rpLW92CO/RTKVa6V8xPPgjWA8imGVLmI4cb+Ru3rWNj2ptJG+J8nOIY1How48NHgPe+kt/YZe//qO78XeZJYJ5KTVVeeOTsafk5NPMXx0CL02ezlOcPFdU8mK684dPRnBuFT5pAu5LJhdtqZnD+My3kFE70fAhYbt+PGKfJLvYPt57U0FJ9a8DgXhrxqN/aqkw3HuS3INi0IQvO1CmgL+rhxREKeRVkCmOcKGdAlWIBglnaTWuEFUNQgn58H+ULSLqB/qTtdO5rbGbmADbVtm8L790vz50J4L7pzwJ9cf)
This is great but means that every old sketch is un-viewable (without copying the code to a new sketch).
Is it possible to build a migration script to update the old sketch links. Or perhaps, add a redirection notice to https://www.brangerbriz.com/labs/threejs_playGnd/js/three.min.js?

**Comment by nbriz** [comment]
hey @harryiliffe, so i personally don't have access to that server, but i've asked @pbriz (who does) is they could make a copy of the lib available at that URL (think that would be easier than writing a migration script)

**Comment by ghost** [comment]
Thanks for your quick response, Nick!
Just waiting on @pbriz.

**Comment by nbriz** [comment]
@harryiliffe the library (&& other potential dependencies) are back in place, so sketches should be working now :)
