### ISSUE TITLE
No geometry showing up in GUI window.

### ISSUE THREAD

**Issue by lentoZoom** [nbriz/threejs_playGnd#4]
I'm not sure what the issue could be. I really want to get into this, but can't start. I tried both chrome and firefox with adblock disabled. Java is up to date. 

![screen shot 2013-08-06 at 4 46 21 pm](https://f.cloud.github.com/assets/5177969/921263/7521f66a-fef2-11e2-884f-4e6a0f7889d7.png)
![screen shot 2013-08-06 at 4 46 33 pm](https://f.cloud.github.com/assets/5177969/921264/753503fe-fef2-11e2-8a6e-e63762a4146f.png)

 I'm on a 2009 MBP. OSX 10.8.4 with a NVIDIA GeForce 9600M GT 512 MB

**Comment by nbriz** [comment]
hmmm, that's strange, could you open your javascript console (option + command + j) in chrome and see if there are any errors popping up? Also, could you visit this page http://get.webgl.org/ and see if webGL is working on your browser?

**Comment by lentoZoom** [comment]
Alright. I have the spinning cube on get.webgl.org. Here is the error that I get in chrome: 
[ THREE.WebGLRenderer 59 three.min.js:424
Uncaught TypeError: undefined is not a function BBGLobjs.js:36
newGeometry BBGLobjs.js:36
MeshObj.make BBGLobjs.js:122
setup threejsplaygnd.brangerbriz.net/gui/:106
(anonymous function) threejsplaygnd.brangerbriz.net/gui/:134 ]

I have had success with manipulating the code of some of the archived sketches, I just can't start a new one or use the GUI. Thanks for the speedy response!

**Comment by nbriz** [comment]
ah, i think i know what the problem is
i just changed sum stuff, try HARD refreshing your browser now ( shift + command + r )

**Comment by lentoZoom** [comment]
Sha BOOOM! Wonderful! I see a cube! Thanks for the quick fix!

**Comment by nbriz** [comment]
awsum :)
