### ISSUE TITLE
"Script on page used too much memory" error

### ISSUE THREAD

**Issue by es-tab-lished** [nbriz/threejs_playGnd#5]
When I add code from some of the more complicated snippets I get this error message and have to reload the page. 

![screen shot 2013-08-19 at 7 10 12 pm](https://f.cloud.github.com/assets/5266005/990636/cf7b1614-0938-11e3-8026-7cb3eda94ba4.png)

**Comment by nbriz** [comment]
does this happen with more than one snippet? or just the vertices one? 
also, spheres have a shit ton of vertices so it might be that? 
try using a different shape and see what happens.

**Comment by es-tab-lished** [comment]
It just happens with the vertices ones. I tried it with another shape and it worked fine.

**Comment by nbriz** [comment]
right, yea i think this is just an issue with the limitations of the technology at the moment :)
